### ISSUE TITLE
[BUG] `@suppress` wrapping examples in tests suppresses test report

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorPkgSkeleton.jl#36]
@lkdvos I noticed putting `@suppress` here: https://github.com/ITensor/ITensorPkgSkeleton.jl/blob/07abef5da88b498a88cab1ffe2d48bb25f248304/templates/test/test/runtests.jl#L45 suppresses the output of the example tests, which was confusing me since I wasn't sure if they were running properly.

Probably you did that because putting macro calls inside of `@safetestset` fails (or at least I'm having trouble getting that to work). Maybe we can just use `@eval module $(gensym())` there, or we can make our own `@safetestset` that works with macros?

**Comment by mtfishman** [comment]
This issue is less pressing if #37 is implemented since the results of those tests would be captured by the outer testset anyway.

**Comment by lkdvos** [comment]
Yeah, the reason is indeed that putting things inside the macro is a bit tricky. The point is that `@safetestset` does exactly what it promises: It attempts to make sure that no code can leak out or into this specific testset, such that for all intents and purposes this can be considered as a test run in isolation.
Putting `@suppress` inside of the the test code violates that, since that macro is not available in the isolated namespace. 
(This is also why I directly interpolate the `file` into the expression, since you cannot easily access that variable from within the isolated namespace)
In principle it's not too hard to bypass this, or come up with our own `@safetestset`, but something like this probably also works:
```julia
@safetestset $file begin
using Suppressor: @suppress
@suppress include($file)
end
```

**Comment by mtfishman** [comment]
Oh I see, yes that would probably work. I just assumed it was a deeper problem with `@safetestset` since I've had trouble with using macros inside`@safetestset` before, but that solution sounds good (assuming it works).
